### ISSUE TITLE
why is the key file executable?

### ISSUE THREAD

**Issue by rgardam** [saltstack-formulas/openvpn-client-formula#3]
````
/etc/openvpn/{{ grains['id'] }}.key:
  file.managed:
    - source: salt://openvpn-client/keys/{{ grains['id'] }}.key
    - mode: 700
````
This to me should be 

````
/etc/openvpn/{{ grains['id'] }}.key:
  file.managed:
    - source: salt://openvpn-client/keys/{{ grains['id'] }}.key
    - mode: 600
````
